// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// (or `yarn cf-typegen`). `RATE_LIMITER`/`RateLimit` and the secrets were added by hand because
// `RateLimit` isn't in the pinned `2023-07-01` workers-types; cf-typegen will reconcile them.
interface RateLimit {
  limit(options: { key: string }): Promise<{ success: boolean }>;
}

interface CloudflareBindings {
  // Nebius Token Factory key for /ai/txt2txt (secret, not in source).
  AI_KEY: string;
  // Cloudflare AI-Gateway token for the Replicate routes (secret, not in source).
  AI_GATEWAY_TOKEN: string;
  AI_GATEWAY_ACCOUNT_ID: string;
  AI_GATEWAY_ID: string;
  IMG_MODEL?: string;
  // Shared bearer secret the app sends as `Authorization: Bearer <APP_SECRET>` (secret, not in source).
  APP_SECRET: string;
  // Native per-IP rate limiter (configured in wrangler.toml under [[unsafe.bindings]]).
  RATE_LIMITER: RateLimit;
}
