// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  AI_KEY: string;
  OPENAPI_KEY: string;
  REPLICATE_API_TOKEN: string;
  IMG_MODEL?: string;
  AI: Ai;
}
