// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// (or `yarn cf-typegen`). `RATE_LIMITER`/`RateLimit` and `APP_SECRET` were added by hand because
// `RateLimit` isn't in the pinned `2023-07-01` workers-types; cf-typegen will reconcile them.
interface RateLimit {
  limit(options: { key: string }): Promise<{ success: boolean }>;
}

interface CloudflareBindings {
  AI_KEY: string;
  OPENAPI_KEY: string;
  REPLICATE_API_TOKEN: string;
  IMG_MODEL?: string;
  AI: Ai;
  // Shared bearer secret the app sends as `Authorization: Bearer <APP_SECRET>` (secret, not in source).
  APP_SECRET: string;
  // Native per-IP rate limiter (configured in wrangler.toml under [[unsafe.bindings]]).
  RATE_LIMITER: RateLimit;
}
